version: '2'
services:
  webserver:
    build: .
    ports:
    - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
        - REDIS_HOSTNAME=redis
        - MONOLOG_STREAM=STDOUT
  redis :
    image : redis
